name: New Relic Agent tests

on: push

jobs:
  test-agent:
    name: Test Agent (8.0.0)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agent-version: ['8.0.0', '7.9.0']
    env:
      NEW_RELIC_VERSION: ${{ matrix.agent-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8
      - name: Download agent
        run: |
          wget --progress=dot:giga https://download.newrelic.com/newrelic/java-agent/newrelic-agent/${NEW_RELIC_VERSION}/newrelic-agent-${NEW_RELIC_VERSION}.jar
          mv newrelic-agent*.jar /newrelic.jar
      - name: Run Tests
        run: mvn test -DargLine="-javaagent:/newrelic.jar" -Dnewrelic-agent.version=${NEW_RELIC_VERSION}